### ISSUE TITLE
Babelfont 2.0 / NFSF todo list

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/babelfont#14]
- [ ] Read truetype and opentype binaries
- [ ] Thoroughly test UFO reading
- [ ] UFO writing
- [ ] More thorough Glyphs test files
- [ ] Test glyphs saving
- [ ] Read/write Fontlab
- [ ] Document all methods
